cc_test(
    name = "test_wait",
    srcs = ["test_wait.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_file",
    srcs = ["test_file.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_sleep",
    srcs = ["test_sleep.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)
