cc_test(
    name = "test_wait",
    srcs = ["test_wait.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_file",
    srcs = ["test_file.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_sleep",
    srcs = ["test_sleep.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_latch",
    srcs = ["test_latch.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_go",
    srcs = ["test_go.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_generic_awaiter",
    srcs = ["test_generic_awaiter.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_future",
    srcs = ["test_future.cpp"],
    deps = [
        "//:common",
    ],
    linkopts = ["-lgtest"],
)

cc_test(
    name = "test_http",
    srcs = ["test_http.cpp"],
    deps = [
        "//:common",
        "//:http",
    ],
    linkopts = ["-lgtest"],
)
