cc_binary(
    name = "helloworld",
    srcs = ["ex001-helloworld.cpp"],
    deps = [
        "//:common",
        "//:http",
    ],
)

cc_binary(
    name = "http_get",
    srcs = ["ex002-http_get.cpp"],
    deps = [
        "//:common",
        "//:http",
    ],
)

cc_binary(
    name = "http_hello_server",
    srcs = ["ex003-http_hello_server.cpp"],
    deps = [
        "//:common",
        "//:http",
    ],
)

cc_binary(
    name = "word_count",
    srcs = ["ex004-word_count.cpp"],
    deps = [
        "//:common",
    ],
)

cc_binary(
    name = "merge_sort",
    srcs = ["ex005-merge_sort.cpp"],
    deps = [
        "//:common",
    ],
    #linkopts = ["-ltbb"],
)

cc_binary(
    name = "http_proxy",
    srcs = ["ex006-http_proxy.cpp"],
    deps = [
        "//:common",
        "//:http",
    ],
)
